//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.Channels = new HashSet<Channel>();
            this.Messages = new HashSet<Message>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string ProfilePicture { get; set; }
    
        public virtual ICollection<Channel> Channels { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual AspNetUserManagement AspNetUserManagement { get; set; }
    }
}
