<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Messages.aspx.cs" Inherits="Twitter.Admin.Messages" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h1 class="main-content-heading" runat="server" id="ChannelNameHolder"></h1>
    <asp:GridView runat="server" ID="GridViewMessages"
        AutoGenerateColumns="false"
        AutoGenerateEditButton="true" UpdateMethod="GridViewMessages_UpdateItem"
        AutoGenerateDeleteButton="true" DeleteMethod="GridViewMessages_DeleteItem"
        DataKeyNames="MessageId"
        ItemType="Twitter.Models.Message" CssClass="table"
        SelectMethod="GridViewChannels_GetData"
        AllowPaging="true" PageSize="5" AllowSorting="true">
        <Columns>
            <asp:TemplateField>
                <HeaderTemplate>
                    Creator
                </HeaderTemplate>
                <ItemTemplate>
                       <asp:LinkButton runat="server" Text="<%#: Item.AspNetUser.UserName %>"
                         PostBackUrl='<%# String.Format("~/UserProfile.aspx?username={0}", Eval("AspNetUser.UserName").ToString()) %>' />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Content" SortExpression="MessageContent">

                <ItemTemplate>
                    <asp:LinkButton Text="<%#:Item.MessageContent%>" runat="server"
                        CommandArgument="<%#:Item.MessageId%>" OnCommand="ViewMessageInfo_Command" />
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="TextBoxEditChannel" Text="<%#: BindItem.MessageContent %>" />
                </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <asp:TextBox ID="MessageContent" runat="server" />
    <asp:LinkButton CssClass="btn btn-primary" runat="server" ID="HyperLinkAddMessage" OnClick="HyperLinkAddMessage_Click" Text="Add Message" />

    <asp:Panel runat="server" ID="PanelMessageInfoHolder">
        <asp:Literal Text="Message Id" runat="server" />
        <asp:Label ID="LabelMessageId" Text="" runat="server" />
        <br />
        <asp:Literal Text="Message Creator" runat="server" />
        <asp:Label ID="LabelMessageCreator" Text="" runat="server" />
        <br />
        <asp:Literal Text="Message Content" runat="server" />
        <asp:Label ID="LabelMessageContent" Text="" runat="server" />
        <br />
        <asp:Literal Text="Message Post Date" runat="server" />
        <asp:Label ID="LabelMessageDate" Text="" runat="server" />
    </asp:Panel>
</asp:Content>
